### ISSUE TITLE
Switch tckrefactor branch to main branch

### ISSUE THREAD

**Issue by starksm64** [jakartaee/platform-tck#1386]

**Comment by scottmarlow** [comment]
The TCK branch rename will happen on July 20, 2024.

After the `tckrefactor` branch is renamed to `main`, we will locally update local clones of the Platform TCK to use the `main` branch name instead of `tckrefactor`:

"[Updating a local clone after a branch name changes](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch#updating-a-local-clone-after-a-branch-name-changes)

After you rename a branch in a repository on GitHub, any collaborator with a local clone of the repository will need to update the clone.

From the local clone of the repository on a computer, run the following commands to update the name of the default branch.

- git branch -m OLD-BRANCH-NAME NEW-BRANCH-NAME
- git fetch origin
- git branch -u origin/NEW-BRANCH-NAME NEW-BRANCH-NAME
- git remote set-head origin -a

Optionally, run the following command to remove tracking references to the old branch name.

git remote prune origin
"

So, locally, I will do the following in my local Platform TCK clone:

"
- git branch -m tckrefactor main
- git fetch origin
- git branch -u origin/main main
- git remote set-head origin -a
"

**Comment by scottmarlow** [comment]
Will now change `tckrefactor` to `main` and `master` to `notmaster` (can pick a better name later for notmaster).

**Comment by scottmarlow** [comment]
The `tckrefactor` branch is now `main`
