### ISSUE TITLE
Update the root pom to Arquillian 1.9.1.Final and add dependencies to module poms

### ISSUE THREAD

**Issue by starksm64** [jakartaee/platform-tck#1410]
arquillian.version in the root pom.xml should be 1.9.1.Final and the module pom.xml files should be updated to have the correct arquillian dependencies so that the tck-rewrite generated code compiles.

Any runner profiles should have dependencies on the  following jakartaee-tck-tools artifacts:

```
     <version.jakarta.tck.arquillian>1.0.0-M1</version.jakarta.tck.arquillian
...
        <dependency>
            <groupId>jakarta.tck.arquillian</groupId>
            <artifactId>arquillian-protocol-appclient</artifactId>
            <version>${version.jakarta.tck.arquillian}</version>
        </dependency>
        <dependency>
            <groupId>jakarta.tck.arquillian</groupId>
            <artifactId>arquillian-protocol-javatest</artifactId>
            <version>${version.jakarta.tck.arquillian}</version>
        </dependency>
        <dependency>
            <groupId>jakarta.tck.arquillian</groupId>
            <artifactId>tck-porting-lib</artifactId>
            <version>${version.jakarta.tck.arquillian}</version>
        </dependency>
```

**Comment by starksm64** [comment]
To be assigned to @edburns

**Comment by edburns** [comment]
Absolute newbie question (pardon my ignorance): Please confirm the work for [1410](https://github.com/jakartaee/platform-tck/issues/1410) is to be done on the main branch.

**Comment by edburns** [comment]
Greetings Programs,

I am seeking review for https://github.com/jakartaee/platform-tck/pull/1441 . I note the check job failed: https://github.com/jakartaee/platform-tck/actions/runs/10292592382 . If I must get a clean run from that job, please let me know and I'll make that happen. If the PR can be worked with as-is, I'd prefer it, because I have no further time to spend on TCK-1410 this week.

Thanks,

Ed
